// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package repo

import (
	"context"
)

// iteratorForCreateRecipientsBatch implements pgx.CopyFromSource.
type iteratorForCreateRecipientsBatch struct {
	rows                 []CreateRecipientsBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateRecipientsBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateRecipientsBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].NotificationID,
		r.rows[0].UserID,
	}, nil
}

func (r iteratorForCreateRecipientsBatch) Err() error {
	return nil
}

func (q *Queries) CreateRecipientsBatch(ctx context.Context, arg []CreateRecipientsBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"notification_recipients"}, []string{"notification_id", "user_id"}, &iteratorForCreateRecipientsBatch{rows: arg})
}
