// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: device_subscriptions.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countActiveSubscriptionsByUser = `-- name: CountActiveSubscriptionsByUser :one
SELECT COUNT(*) FROM device_subscriptions
WHERE user_id = $1 AND is_active = true
`

func (q *Queries) CountActiveSubscriptionsByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSubscriptionsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeviceSubscription = `-- name: CreateDeviceSubscription :one
INSERT INTO device_subscriptions (
  user_id,
  endpoint,
  p256dh,
  auth,
  device_id,
  user_agent,
  locale,
  timezone
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, user_id, endpoint, p256dh, auth, device_id, user_agent, locale, timezone, is_active, created_at, updated_at
`

type CreateDeviceSubscriptionParams struct {
	UserID    string  `json:"user_id"`
	Endpoint  string  `json:"endpoint"`
	P256dh    string  `json:"p256dh"`
	Auth      string  `json:"auth"`
	DeviceID  *string `json:"device_id"`
	UserAgent *string `json:"user_agent"`
	Locale    *string `json:"locale"`
	Timezone  *string `json:"timezone"`
}

func (q *Queries) CreateDeviceSubscription(ctx context.Context, arg CreateDeviceSubscriptionParams) (DeviceSubscription, error) {
	row := q.db.QueryRow(ctx, createDeviceSubscription,
		arg.UserID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
		arg.DeviceID,
		arg.UserAgent,
		arg.Locale,
		arg.Timezone,
	)
	var i DeviceSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.DeviceID,
		&i.UserAgent,
		&i.Locale,
		&i.Timezone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateDeviceSubscription = `-- name: DeactivateDeviceSubscription :exec
UPDATE device_subscriptions
SET is_active = false, updated_at = now()
WHERE id = $1
`

func (q *Queries) DeactivateDeviceSubscription(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateDeviceSubscription, id)
	return err
}

const deleteDeviceSubscription = `-- name: DeleteDeviceSubscription :exec
DELETE FROM device_subscriptions
WHERE id = $1
`

func (q *Queries) DeleteDeviceSubscription(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeviceSubscription, id)
	return err
}

const deleteDeviceSubscriptionByEndpoint = `-- name: DeleteDeviceSubscriptionByEndpoint :exec
DELETE FROM device_subscriptions
WHERE endpoint = $1
`

func (q *Queries) DeleteDeviceSubscriptionByEndpoint(ctx context.Context, endpoint string) error {
	_, err := q.db.Exec(ctx, deleteDeviceSubscriptionByEndpoint, endpoint)
	return err
}

const findStaleSubscriptions = `-- name: FindStaleSubscriptions :many
SELECT id, user_id, endpoint, p256dh, auth, device_id, user_agent, locale, timezone, is_active, created_at, updated_at FROM device_subscriptions
WHERE is_active = true
  AND updated_at < $1
ORDER BY updated_at ASC
LIMIT $2
`

type FindStaleSubscriptionsParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) FindStaleSubscriptions(ctx context.Context, arg FindStaleSubscriptionsParams) ([]DeviceSubscription, error) {
	rows, err := q.db.Query(ctx, findStaleSubscriptions, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceSubscription{}
	for rows.Next() {
		var i DeviceSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.DeviceID,
			&i.UserAgent,
			&i.Locale,
			&i.Timezone,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeviceSubscription = `-- name: GetDeviceSubscription :one
SELECT id, user_id, endpoint, p256dh, auth, device_id, user_agent, locale, timezone, is_active, created_at, updated_at FROM device_subscriptions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDeviceSubscription(ctx context.Context, id uuid.UUID) (DeviceSubscription, error) {
	row := q.db.QueryRow(ctx, getDeviceSubscription, id)
	var i DeviceSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.DeviceID,
		&i.UserAgent,
		&i.Locale,
		&i.Timezone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceSubscriptionByEndpoint = `-- name: GetDeviceSubscriptionByEndpoint :one
SELECT id, user_id, endpoint, p256dh, auth, device_id, user_agent, locale, timezone, is_active, created_at, updated_at FROM device_subscriptions
WHERE endpoint = $1 LIMIT 1
`

func (q *Queries) GetDeviceSubscriptionByEndpoint(ctx context.Context, endpoint string) (DeviceSubscription, error) {
	row := q.db.QueryRow(ctx, getDeviceSubscriptionByEndpoint, endpoint)
	var i DeviceSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.DeviceID,
		&i.UserAgent,
		&i.Locale,
		&i.Timezone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveDeviceSubscriptionsByUser = `-- name: ListActiveDeviceSubscriptionsByUser :many
SELECT id, user_id, endpoint, p256dh, auth, device_id, user_agent, locale, timezone, is_active, created_at, updated_at FROM device_subscriptions
WHERE user_id = $1 AND is_active = true
ORDER BY created_at DESC
`

func (q *Queries) ListActiveDeviceSubscriptionsByUser(ctx context.Context, userID string) ([]DeviceSubscription, error) {
	rows, err := q.db.Query(ctx, listActiveDeviceSubscriptionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceSubscription{}
	for rows.Next() {
		var i DeviceSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.DeviceID,
			&i.UserAgent,
			&i.Locale,
			&i.Timezone,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceSubscriptionsByUser = `-- name: ListDeviceSubscriptionsByUser :many
SELECT id, user_id, endpoint, p256dh, auth, device_id, user_agent, locale, timezone, is_active, created_at, updated_at FROM device_subscriptions
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDeviceSubscriptionsByUser(ctx context.Context, userID string) ([]DeviceSubscription, error) {
	rows, err := q.db.Query(ctx, listDeviceSubscriptionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceSubscription{}
	for rows.Next() {
		var i DeviceSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.DeviceID,
			&i.UserAgent,
			&i.Locale,
			&i.Timezone,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeviceSubscription = `-- name: UpdateDeviceSubscription :one
UPDATE device_subscriptions
SET
  p256dh = COALESCE($1, p256dh),
  auth = COALESCE($2, auth),
  device_id = COALESCE($3, device_id),
  user_agent = COALESCE($4, user_agent),
  locale = COALESCE($5, locale),
  timezone = COALESCE($6, timezone),
  is_active = COALESCE($7, is_active),
  updated_at = now()
WHERE id = $8
RETURNING id, user_id, endpoint, p256dh, auth, device_id, user_agent, locale, timezone, is_active, created_at, updated_at
`

type UpdateDeviceSubscriptionParams struct {
	P256dh    *string   `json:"p256dh"`
	Auth      *string   `json:"auth"`
	DeviceID  *string   `json:"device_id"`
	UserAgent *string   `json:"user_agent"`
	Locale    *string   `json:"locale"`
	Timezone  *string   `json:"timezone"`
	IsActive  *bool     `json:"is_active"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) UpdateDeviceSubscription(ctx context.Context, arg UpdateDeviceSubscriptionParams) (DeviceSubscription, error) {
	row := q.db.QueryRow(ctx, updateDeviceSubscription,
		arg.P256dh,
		arg.Auth,
		arg.DeviceID,
		arg.UserAgent,
		arg.Locale,
		arg.Timezone,
		arg.IsActive,
		arg.ID,
	)
	var i DeviceSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.DeviceID,
		&i.UserAgent,
		&i.Locale,
		&i.Timezone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
