// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DeviceSubscription struct {
	ID        uuid.UUID `json:"id"`
	UserID    string    `json:"user_id"`
	Endpoint  string    `json:"endpoint"`
	P256dh    string    `json:"p256dh"`
	Auth      string    `json:"auth"`
	DeviceID  *string   `json:"device_id"`
	UserAgent *string   `json:"user_agent"`
	Locale    *string   `json:"locale"`
	Timezone  *string   `json:"timezone"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Notification struct {
	ID             uuid.UUID       `json:"id"`
	IdempotencyKey *string         `json:"idempotency_key"`
	Type           string          `json:"type"`
	Title          *string         `json:"title"`
	Body           *string         `json:"body"`
	Icon           *string         `json:"icon"`
	Url            *string         `json:"url"`
	Locale         *string         `json:"locale"`
	Data           json.RawMessage `json:"data"`
	Status         string          `json:"status"`
	DedupeKey      *string         `json:"dedupe_key"`
	TtlSeconds     *int32          `json:"ttl_seconds"`
	Priority       *string         `json:"priority"`
	CreatedAt      time.Time       `json:"created_at"`
}

type NotificationAttempt struct {
	ID             uuid.UUID   `json:"id"`
	NotificationID uuid.UUID   `json:"notification_id"`
	SubscriptionID pgtype.UUID `json:"subscription_id"`
	UserID         string      `json:"user_id"`
	Status         string      `json:"status"`
	HttpStatus     *int32      `json:"http_status"`
	LatencyMs      *int32      `json:"latency_ms"`
	Error          *string     `json:"error"`
	RetryCount     *int32      `json:"retry_count"`
	Pruned         bool        `json:"pruned"`
	CreatedAt      time.Time   `json:"created_at"`
}

type NotificationRecipient struct {
	NotificationID uuid.UUID `json:"notification_id"`
	UserID         string    `json:"user_id"`
}
