// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package repo

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countNotificationsByStatus = `-- name: CountNotificationsByStatus :one
SELECT COUNT(*) FROM notifications
WHERE status = $1
`

func (q *Queries) CountNotificationsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countNotificationsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
  idempotency_key,
  type,
  title,
  body,
  icon,
  url,
  locale,
  data,
  status,
  dedupe_key,
  ttl_seconds,
  priority
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, idempotency_key, type, title, body, icon, url, locale, data, status, dedupe_key, ttl_seconds, priority, created_at
`

type CreateNotificationParams struct {
	IdempotencyKey *string         `json:"idempotency_key"`
	Type           string          `json:"type"`
	Title          *string         `json:"title"`
	Body           *string         `json:"body"`
	Icon           *string         `json:"icon"`
	Url            *string         `json:"url"`
	Locale         *string         `json:"locale"`
	Data           json.RawMessage `json:"data"`
	Status         string          `json:"status"`
	DedupeKey      *string         `json:"dedupe_key"`
	TtlSeconds     *int32          `json:"ttl_seconds"`
	Priority       *string         `json:"priority"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.IdempotencyKey,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Icon,
		arg.Url,
		arg.Locale,
		arg.Data,
		arg.Status,
		arg.DedupeKey,
		arg.TtlSeconds,
		arg.Priority,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Icon,
		&i.Url,
		&i.Locale,
		&i.Data,
		&i.Status,
		&i.DedupeKey,
		&i.TtlSeconds,
		&i.Priority,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications
WHERE id = $1
`

func (q *Queries) DeleteNotification(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteNotification, id)
	return err
}

const deleteOldNotifications = `-- name: DeleteOldNotifications :exec
DELETE FROM notifications
WHERE created_at < $1
`

func (q *Queries) DeleteOldNotifications(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteOldNotifications, createdAt)
	return err
}

const findNotificationsByDedupeKey = `-- name: FindNotificationsByDedupeKey :many
SELECT id, idempotency_key, type, title, body, icon, url, locale, data, status, dedupe_key, ttl_seconds, priority, created_at FROM notifications
WHERE dedupe_key = $1
  AND created_at > $2
ORDER BY created_at DESC
`

type FindNotificationsByDedupeKeyParams struct {
	DedupeKey *string   `json:"dedupe_key"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) FindNotificationsByDedupeKey(ctx context.Context, arg FindNotificationsByDedupeKeyParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, findNotificationsByDedupeKey, arg.DedupeKey, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.IdempotencyKey,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Icon,
			&i.Url,
			&i.Locale,
			&i.Data,
			&i.Status,
			&i.DedupeKey,
			&i.TtlSeconds,
			&i.Priority,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotification = `-- name: GetNotification :one
SELECT id, idempotency_key, type, title, body, icon, url, locale, data, status, dedupe_key, ttl_seconds, priority, created_at FROM notifications
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetNotification(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Icon,
		&i.Url,
		&i.Locale,
		&i.Data,
		&i.Status,
		&i.DedupeKey,
		&i.TtlSeconds,
		&i.Priority,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationByIdempotencyKey = `-- name: GetNotificationByIdempotencyKey :one
SELECT id, idempotency_key, type, title, body, icon, url, locale, data, status, dedupe_key, ttl_seconds, priority, created_at FROM notifications
WHERE idempotency_key = $1 LIMIT 1
`

func (q *Queries) GetNotificationByIdempotencyKey(ctx context.Context, idempotencyKey *string) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByIdempotencyKey, idempotencyKey)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Icon,
		&i.Url,
		&i.Locale,
		&i.Data,
		&i.Status,
		&i.DedupeKey,
		&i.TtlSeconds,
		&i.Priority,
		&i.CreatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, idempotency_key, type, title, body, icon, url, locale, data, status, dedupe_key, ttl_seconds, priority, created_at FROM notifications
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListNotificationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.IdempotencyKey,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Icon,
			&i.Url,
			&i.Locale,
			&i.Data,
			&i.Status,
			&i.DedupeKey,
			&i.TtlSeconds,
			&i.Priority,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsByStatus = `-- name: ListNotificationsByStatus :many
SELECT id, idempotency_key, type, title, body, icon, url, locale, data, status, dedupe_key, ttl_seconds, priority, created_at FROM notifications
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListNotificationsByStatus(ctx context.Context, arg ListNotificationsByStatusParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.IdempotencyKey,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Icon,
			&i.Url,
			&i.Locale,
			&i.Data,
			&i.Status,
			&i.DedupeKey,
			&i.TtlSeconds,
			&i.Priority,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationStatus = `-- name: UpdateNotificationStatus :one
UPDATE notifications
SET status = $2
WHERE id = $1
RETURNING id, idempotency_key, type, title, body, icon, url, locale, data, status, dedupe_key, ttl_seconds, priority, created_at
`

type UpdateNotificationStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) (Notification, error) {
	row := q.db.QueryRow(ctx, updateNotificationStatus, arg.ID, arg.Status)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Icon,
		&i.Url,
		&i.Locale,
		&i.Data,
		&i.Status,
		&i.DedupeKey,
		&i.TtlSeconds,
		&i.Priority,
		&i.CreatedAt,
	)
	return i, err
}
