// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckRecipientExists(ctx context.Context, arg CheckRecipientExistsParams) (bool, error)
	CountActiveSubscriptionsByUser(ctx context.Context, userID string) (int64, error)
	CountDeliveryAttemptsByNotification(ctx context.Context, notificationID uuid.UUID) (int64, error)
	CountDeliveryAttemptsByStatus(ctx context.Context, status string) (int64, error)
	CountNotificationsByStatus(ctx context.Context, status string) (int64, error)
	CountRecipientsByNotification(ctx context.Context, notificationID uuid.UUID) (int64, error)
	CreateDeliveryAttempt(ctx context.Context, arg CreateDeliveryAttemptParams) (NotificationAttempt, error)
	CreateDeviceSubscription(ctx context.Context, arg CreateDeviceSubscriptionParams) (DeviceSubscription, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateRecipient(ctx context.Context, arg CreateRecipientParams) error
	CreateRecipientsBatch(ctx context.Context, arg []CreateRecipientsBatchParams) (int64, error)
	DeactivateDeviceSubscription(ctx context.Context, id uuid.UUID) error
	DeleteDeviceSubscription(ctx context.Context, id uuid.UUID) error
	DeleteDeviceSubscriptionByEndpoint(ctx context.Context, endpoint string) error
	DeleteNotification(ctx context.Context, id uuid.UUID) error
	DeleteOldAttempts(ctx context.Context, createdAt time.Time) error
	DeleteOldNotifications(ctx context.Context, createdAt time.Time) error
	DeleteRecipient(ctx context.Context, arg DeleteRecipientParams) error
	DeleteRecipientsByNotification(ctx context.Context, notificationID uuid.UUID) error
	FindFailedAttemptsBySubscription(ctx context.Context, arg FindFailedAttemptsBySubscriptionParams) ([]NotificationAttempt, error)
	FindNotificationsByDedupeKey(ctx context.Context, arg FindNotificationsByDedupeKeyParams) ([]Notification, error)
	FindStaleSubscriptions(ctx context.Context, arg FindStaleSubscriptionsParams) ([]DeviceSubscription, error)
	GetDeliveryAttempt(ctx context.Context, id uuid.UUID) (NotificationAttempt, error)
	GetDeliveryStats(ctx context.Context, createdAt time.Time) (GetDeliveryStatsRow, error)
	GetDeviceSubscription(ctx context.Context, id uuid.UUID) (DeviceSubscription, error)
	GetDeviceSubscriptionByEndpoint(ctx context.Context, endpoint string) (DeviceSubscription, error)
	GetNotification(ctx context.Context, id uuid.UUID) (Notification, error)
	GetNotificationByIdempotencyKey(ctx context.Context, idempotencyKey *string) (Notification, error)
	GetRecipientsByNotification(ctx context.Context, notificationID uuid.UUID) ([]NotificationRecipient, error)
	GetRecipientsByUser(ctx context.Context, userID string) ([]NotificationRecipient, error)
	ListActiveDeviceSubscriptionsByUser(ctx context.Context, userID string) ([]DeviceSubscription, error)
	ListDeliveryAttemptsByNotification(ctx context.Context, notificationID uuid.UUID) ([]NotificationAttempt, error)
	ListDeliveryAttemptsByStatus(ctx context.Context, arg ListDeliveryAttemptsByStatusParams) ([]NotificationAttempt, error)
	ListDeliveryAttemptsBySubscription(ctx context.Context, arg ListDeliveryAttemptsBySubscriptionParams) ([]NotificationAttempt, error)
	ListDeliveryAttemptsByUser(ctx context.Context, arg ListDeliveryAttemptsByUserParams) ([]NotificationAttempt, error)
	ListDeviceSubscriptionsByUser(ctx context.Context, userID string) ([]DeviceSubscription, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	ListNotificationsByStatus(ctx context.Context, arg ListNotificationsByStatusParams) ([]Notification, error)
	MarkSubscriptionAsPruned(ctx context.Context, subscriptionID pgtype.UUID) error
	UpdateDeliveryAttemptStatus(ctx context.Context, arg UpdateDeliveryAttemptStatusParams) (NotificationAttempt, error)
	UpdateDeviceSubscription(ctx context.Context, arg UpdateDeviceSubscriptionParams) (DeviceSubscription, error)
	UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) (Notification, error)
}

var _ Querier = (*Queries)(nil)
