// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recipients.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const checkRecipientExists = `-- name: CheckRecipientExists :one
SELECT EXISTS(
  SELECT 1 FROM notification_recipients
  WHERE notification_id = $1 AND user_id = $2
)
`

type CheckRecipientExistsParams struct {
	NotificationID uuid.UUID `json:"notification_id"`
	UserID         string    `json:"user_id"`
}

func (q *Queries) CheckRecipientExists(ctx context.Context, arg CheckRecipientExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkRecipientExists, arg.NotificationID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countRecipientsByNotification = `-- name: CountRecipientsByNotification :one
SELECT COUNT(*) FROM notification_recipients
WHERE notification_id = $1
`

func (q *Queries) CountRecipientsByNotification(ctx context.Context, notificationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRecipientsByNotification, notificationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRecipient = `-- name: CreateRecipient :exec
INSERT INTO notification_recipients (
  notification_id,
  user_id
) VALUES (
  $1, $2
)
ON CONFLICT (notification_id, user_id) DO NOTHING
`

type CreateRecipientParams struct {
	NotificationID uuid.UUID `json:"notification_id"`
	UserID         string    `json:"user_id"`
}

func (q *Queries) CreateRecipient(ctx context.Context, arg CreateRecipientParams) error {
	_, err := q.db.Exec(ctx, createRecipient, arg.NotificationID, arg.UserID)
	return err
}

type CreateRecipientsBatchParams struct {
	NotificationID uuid.UUID `json:"notification_id"`
	UserID         string    `json:"user_id"`
}

const deleteRecipient = `-- name: DeleteRecipient :exec
DELETE FROM notification_recipients
WHERE notification_id = $1 AND user_id = $2
`

type DeleteRecipientParams struct {
	NotificationID uuid.UUID `json:"notification_id"`
	UserID         string    `json:"user_id"`
}

func (q *Queries) DeleteRecipient(ctx context.Context, arg DeleteRecipientParams) error {
	_, err := q.db.Exec(ctx, deleteRecipient, arg.NotificationID, arg.UserID)
	return err
}

const deleteRecipientsByNotification = `-- name: DeleteRecipientsByNotification :exec
DELETE FROM notification_recipients
WHERE notification_id = $1
`

func (q *Queries) DeleteRecipientsByNotification(ctx context.Context, notificationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecipientsByNotification, notificationID)
	return err
}

const getRecipientsByNotification = `-- name: GetRecipientsByNotification :many
SELECT notification_id, user_id FROM notification_recipients
WHERE notification_id = $1
ORDER BY user_id
`

func (q *Queries) GetRecipientsByNotification(ctx context.Context, notificationID uuid.UUID) ([]NotificationRecipient, error) {
	rows, err := q.db.Query(ctx, getRecipientsByNotification, notificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationRecipient{}
	for rows.Next() {
		var i NotificationRecipient
		if err := rows.Scan(&i.NotificationID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecipientsByUser = `-- name: GetRecipientsByUser :many
SELECT notification_id, user_id FROM notification_recipients
WHERE user_id = $1
ORDER BY notification_id
`

func (q *Queries) GetRecipientsByUser(ctx context.Context, userID string) ([]NotificationRecipient, error) {
	rows, err := q.db.Query(ctx, getRecipientsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationRecipient{}
	for rows.Next() {
		var i NotificationRecipient
		if err := rows.Scan(&i.NotificationID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
